### ISSUE TITLE
error in composer install

### ISSUE THREAD

**Issue by meghakundu** [Alaa-Dawoud/blogger-with-laravel#1]
@Alaa-Dawoud Please kindly look into it.
![image](https://github.com/Alaa-Dawoud/blogger-with-laravel/assets/54468245/05a40464-e1a4-42d7-8821-3ebc98e97935)

**Comment by Alaa-Dawoud** [comment]
Hi @meghakundu I hope you are doing well.

You can try again now. And according to the translation I found a package called astrotomic which is very great for content translation but you can also use Lang.

Regards
Alaa
